### ISSUE TITLE
"Attempt to decode JSON with unexpected mimetype: application/octet-stream" for json artifact served by Bamboo

### ISSUE THREAD

**Issue by walterdeboer** [ICTU/quality-time#1325]
I've added a job to generate  "npm outdated --json > npm-outdated.json" When serving it to Quality Time, the following error occurs:

```
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 127, in __safely_parse_source_responses
    value, total, entities = await self._parse_source_responses(responses)
  File "/home/collector/source_collectors/file_source_collectors/npm.py", line 19, in _parse_source_responses
    installed_dependencies.update(await response.json())
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://bamboo.shs.cjib.minjus.nl/browse/CCJ-CCJC-45/artifact/JOB1/npm-outdated.json/npm-outdated.json')
```

See https://stackoverflow.com/questions/48840378/python-attempt-to-decode-json-with-unexpected-mimetype

**Comment by fniessink** [comment]
Hi Walter, thanks for reporting this. Instead of fixing (working around) this specifically for the npm outdated dependencies source, I'd prefer a solution that works for all JSONFileSourceCollectors by turning off the content-type check for [aiohttp.ClientResponse.json()](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponse.json) more widely so we don't run into this issue again for other JSON file sources. Do you want to take a stab at this or would you prefer me to do it?

**Comment by walterdeboer** [comment]
Sure, I'll have a look

**Comment by walterdeboer** [comment]
Sorry, not enough Python skilles here... I'll have to work on that ;-)

**Comment by fniessink** [comment]
There was nothing wrong with your Python skills! What I changed was that I limited your changes to just the JSON file collectors (you also changed the the API collectors, but I would expect the content-type of e.g. the GitLab API to always be set correctly; and so far we haven't had problems there). And I updated the CHANGELOG.
