### ISSUE TITLE
Add support for hiding columns in the report

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#1464]
It could be handy to toggle (enable/disable) columns in the report based on different needs.

**Comment by fniessink** [comment]
You probably want the pdf exports to also hide disabled columns? That means the toggle needs to be saved server side.

**Comment by denniebouman** [comment]
If that is possible, yes please.

**Comment by fniessink** [comment]
Anything is possible ;-) Anyway, I implemented hiding of the columns, but decided not to store the state in the report because it would be weird that if one user hides a column, that column would disappear for all other users too. Also, when someone hides metrics that don't require action, that state isn't stored on the server either.

This means we'll need to find another way to pass the visible columns (and visible rows) to the pdf renderer. If that's possible, it may also make it possible to expand metrics and print trend graphs in the pdf. I've opened a new issue for this: #1466.

**Comment by denniebouman** [comment]
yes, you are right. Good solution for now.
