### ISSUE TITLE
Error when using datepicker

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#1534]
When selecting a Technical debt end date, for accepting technical debt for a certain period. An error occurs. A white screen is displayed and the UI of Quality-Time disappears.

**Comment by fniessink** [comment]
The date picker has a minimum date set to today. Apparently, if the current value of the technical debt end date is far enough in the past so that the whole month popup consists of disabled dates, the date picker will crash. Possibly related: https://github.com/arfedulov/semantic-ui-calendar-react/issues/176 and https://github.com/arfedulov/semantic-ui-calendar-react/issues/202. 

Worked around by removing the minimum date. This makes it possible to set technical end dates in the past, but that shouldn't be a problem as all future end dates become past end dates one day.
