### ISSUE TITLE
Slow overall performance on LRK release report

### ISSUE THREAD

**Issue by cat00man** [ICTU/quality-time#2169]
On the LRK release report (http://www.quality-time.lrk.ictu/34d9b1f0-c8b3-4689-94d8-23f2ec20dc6b) the overall performance is slow.
But especially on the tab Sources and e.g. OWASP ZAP results tab (it takes for ever to get an arrow if even at all) see screenshot below:
![C5cC1tm7hk](https://user-images.githubusercontent.com/38661536/118244673-19781800-b4a0-11eb-9521-5a12653277ad.png)

**Comment by fniessink** [comment]
Two questions:

1. I can't reproduce what's slow about the Sources tab of the OWASP ZAP security warnings, are you still having this issue?
1. I can't reproduce the security warnings status not being editable, because I don't have edit permissions. Can you give me edit permissions on the "measurement entities" so I can check? Thanks.

**Comment by fniessink** [comment]
Closed due to no response.
