### ISSUE TITLE
Add creationDate to issue tracker

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#2628]
Recently the newly added column "Issues" was added to QT, with the issue number and the status (open, closed, etc.) of the issue. 
Feature request: also add the creationDate.

A few examples:
21-09-2021 - PRJ-1234 - Open 
21-09-2021 | PRJ-1234 | Open 
PRJ-1234 - Open - 21-09-2021

Because this will take more space, maybe it is better to add (append) this information to the comment section? And delete the issue column??

**Comment by fniessink** [comment]
@emdv88 will make a first version by adding the issue creation date to the issue column. Let's evaluate that option first.

**Comment by fniessink** [comment]
Erik added the creation date to the issue column, but on review I decided not to include the issue creation date in the issue column. The primary purpose of the issue column is to show the status of the linked issue(s), making issue id and issue status the primary information. When the issue was created is secondary. 

Hence, Quality-time now (I'll make another release candidate soon) shows the creation date of the issue (together with the date of the last update of the issue) in a popup. Similar to how the starting date of the current metric status and the date of the current measurement value are shown in popups only.

I'm still undecided about adding the issue to the comment column.

**Comment by denniebouman** [comment]
OR (suggestion) change the color  - to red for example - of the status of the linked issue, when the (created)date exceeds a (configurable) number of days?? @fniessink

**Comment by fniessink** [comment]
Wouldn't accepting technical debt with an end date give you the same functionality?

**Comment by denniebouman** [comment]
Hi @fniessink as discussed, maybe it is a good idee to make the visibility of the creationDate configurable in the "Issue tracker" tab (for consistency). This way the user decides the look and feel of the UI.
In the issues column it then is possible to list the issue number, status and created date
