### ISSUE TITLE
Allow for using a perm link to a specific metric

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#2925]
It would be great to be able to use a URL to point to a specified metric to go there directly

**Comment by fniessink** [comment]
Some thoughts on this feature request.

**In the metrics details view**, metrics already have an id, so using the metric id as URL hash already works, more or less. Clicking `http://www.quality-time.example.org/example-report-quality-time?tabs=038273af-8d71-4247-8235-fa9da3906a53%3A0#0cf96e46-3688-490d-97e2-2152687c4306` jumps to the metric with id `0cf96e46-3688-490d-97e2-2152687c4306`. Unfortunately, after clicking the metric is under the menubar and thus not visible. This is solved in PR #3018 by adding

```css
html {
    scroll-padding-top: 70px; /* height of sticky header */
}
```

to App.css. Tested with latest Safari, Chrome, and Firefox. Courtesy https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/

Besides fixing the menubar hiding the metric, the other thing needed is a button to copy the permanent link. Open question: where to have the button. I see a few options:

1. A share button next the metric name in the subject tables
2. A share button in the metric configuration tab
3. A new metric tab for sharing, i.e. next to the configuration and change log tabs

The first two options would need some kind of popup that appears after clicking the button to indicate to the user that the URL was copied to the clipboard. The third option could show the URL in the tab together with a "copy link to clipboard" button. Advantage of the third option is that we could also use that method for subjects and reports.

Decision: First implementation will use option 3!

By the way, the link will have one limitation: since it contains both the report id and the metric id the perm link stops working if the metric is moved to another report.
