### ISSUE TITLE
Use the canonical name of users in the change log instead of their user id

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#2930]
If a user logs in with their user id, the user id is used in the change log, making it hard to recognize who did what. If Quality-time would get the canonical name from the LDAP server it could use that name in the change log.

**Comment by fniessink** [comment]
I changed this feature request to what I think the real issue is: users being hard to recognize if Quality-time uses their user id  in the change log.

LDAP has a mandatory attribute for objects, called "Common Name" or CN. We can retrieve that as part of user authentication and store it together with the username and email address in the session. Then in `_prepare_documents_for_insertion()` the CN can be added to the delta description.
