### ISSUE TITLE
Allow for collapsing all expanded metrics at once

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3133]
Have an easy to acces button, available at all times, that can be used to collapse all open metrics at once.

**Comment by fniessink** [comment]
For now, add a "Collapse all metrics" menu item to the hamburger menu. The menu item should be inactive if there are no expanded metrics in the current report. It should be active if there are one or more expanded metrics in the report. Selecting "Collapse all metrics" collapses all metrics **in all subjects** in the current report.

We let the "Collapse all metrics" menu collapse all metrics in the report and not just in the subject because all menu options in the hamburger menu's work for all subjects at the same time. Only collapsing the metrics in the current subject would make the scope of the different hamburger menu items inconsistent.
