### ISSUE TITLE
Some field trigger LastPass password change prompt

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3172]
This is a known issue from LastPass. This also happens to other application.
This morning, a colleague of mine had the same problem. 
It happens when a user opens the sources tab of a metric.
I can provide more details (for reproduction) if required.

I believe this could be easily fixed by changing the field-names.

see also
https://www.ecosia.org/search?q=lastpass%20is%20triggered%20by%20non%20password%20field&addon=opensearch

**Comment by fniessink** [comment]
[Apparently](https://stackoverflow.com/questions/20954944/stop-lastpass-filling-out-a-form), LastPass doesn't fill in fields that have `data-lpignore="true"`, so we can try to add that attribute to username and password fields.

On the other hand, what's the bug here? The sources tab does have username and password fields, so why is it a bug if the LastPass tries to help you with filling in a username and password?

**Comment by Sebastiaan127001** [comment]
The bug here is that Lastpass assumes that the credentials from the source are the credentials from the Quality Time instance and if the user confirms, LastPass overwrites the Quality Time login (ldap) .

**Comment by fniessink** [comment]
Given the LastPass troubles (see for example https://www.theverge.com/2022/12/28/23529547/lastpass-vault-breach-disclosure-encryption-cybersecurity-rebuttal) we won't put energy into supporting LastPass.

**Comment by Sebastiaan127001** [comment]
fully agree
