### ISSUE TITLE
Allow for clickable URL suggestion

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3229]
When a user makes a type in the URL and QT suggests the possible correct URL, it would be useful if the link was clickable.
For instance, you have no protocol added to your URL, do you want to add http:// or https://

![149125521-a932e8c1-5e3d-4ec7-9f87-a15354f2eace](https://user-images.githubusercontent.com/95095453/149145148-71a9ebe4-236c-467f-92cf-ea169f8548e5.png)

**Comment by fniessink** [comment]
The suggestion for a schema comes from an underlying library, not Quality-time itself, so Quality-time would need to parse these error messages looking for URLs. Also, clicking a toaster message closes it, so that behavior would need to be changes as well. The effort doesn't seem worth the benefit of being able to open a URL from a very temporary toaster message.
