### ISSUE TITLE
Move shared code to new component

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#3269]

**Comment by emdv88** [comment]
## Build docker containers from the components folder
actually, it's not necessary to move the Dockerfiles into the components directory as long as the docker build command is executed from the components directory: 
```bash
docker build -t qt-server -f server/Dockerfile .
```
in the docker-compose files, this can be automated as follows:
```yml
services:
  server:
    build:
      context: ../components
      dockerfile: server/Dockerfile
```
all relative paths inside the Dockerfile need to be prepended with server/ for this to work

**caution: this will make the Dockerfile unusable from anywhere accept the components directory**

## How to import the shared code
Generally two options have been considered: pip install as a local package vs adding the shared folder to the PYTHONPATH env variable. Both options have advantages and disadvantages and generally require a bit of tweaking of various configuration files in this repo. 

### Using pip install
The branch `3269-shared-component` contains a POC for using pip install the local package.
Notable downside: the local package has to be installed without hashes. This has been solved by removing the hashes from the requirements-dev.txt, but retaining it in the requirements.txt. For the docker (production) environment, the local package is installed using a separate pip install command in the Dockerfile. In multiple other test and pipeline environments the pip install command had to be separated into two for not requiring hashes in the dev dependencies.

Todo's for this approach: 
- give the shared package it's own unittests and run them
- give the shared package it's own dependencies
- pip-audit cannot audit shared-python dependency and hence crashes. There does not seem to be an ignore option.
- Deepsource Docker fails because the pip install shared-python is not pinned to a version
- for some reason the feature test coverage in circle-ci is not 100%. (locally and in github it is 100%)

### Appending PYTHONPATH
The branch `3269-shared-component-path-addition` contains a POC for adding the shared folder to the PYTHONPATH env variable. The env variable has been added in **quality_time_server.py** and **quality_time_server_under_coverage.py**. Other than that, this approach required some tweaking of the quality-time configuration as well.

Todo's for this approach: 
- expand the PYTHONPATH variable when running unittests aswell
- fix the 'export as pdf' feature test that for some reason fails in the github action (but not in the circle-ci pipeline)

**Comment by emdv88** [comment]
## Suggestion on solution

My preference would go to handling the shared code as a separate package and installing it using `pip install`. This mainly because it is a less hacky way that uses existing infrastructure and routines that are specifically designed to handle shared code usage (package distribution). This ensures a large probability that future developments and needs will be supported as well using this approach, requiring minor changes in the configuration of quality-time.

The one (hypothetical) reason that I see that I would consider a good reason to avoid handling shared_python as a pip package and instead always appending the `PYTHONPATH` with the shared_python folder, would be that if it would take considerable effort to make shared_python a pip package, distribute it, and/or run it in editable mode for debug purposes. However, I think that this spike has shown that that is not the case. 

Hence my suggestion to make shared python a separate python package and a dependency for both internal and external servers. Possible future developments might be:
- see if there is also functionality in the collector and/or notifier that could be reused?
- distribute the shared_python module on PyPi to prevent the local installation
