### ISSUE TITLE
Notify the user why editing is not possible

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3380]
It would be useful to notify the user when the user tries to edit a field when it's not editable.
This can occur in the following situations:

- the user is not logged in
- the user is using the 'time machine' functionality where he/she looks into a view of the past, fields are not editable on purpose

**Comment by fniessink** [comment]
The first bullet point will be fixed by #5327. The second bullet point could be fixed by making it more clear in the user interface that the user is time traveling (or looking at at tag report, those are read only too):

implement an onClick handler for all widgets that fire a toast when the widget is read-only with the reason why (either nog logged in or user is viewing a tag report).

**Comment by fniessink** [comment]
What I ended up implementing: Quality-time notifies the user that editing is not possible via a toaster message on these events:
- [x] When the page is loaded and there is no active user session
- [x] When the user opens a tag report
- [x] When the user time travels to a past date
- [ ] Except exporting to pdf
