### ISSUE TITLE
Artefacts of GitLab jobs that aren't in the latest run, cannot be obtained via a single URL in the GitLab API

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#4113]
**Describe the bug**
Artefacts of GitLab jobs that aren't in the latest run, cannot be obtained via a single URL in the GitLab API.
When a job has run in a scheduled build and the artefacts did not expire, the artefacts cannot be downloaded though the REST API when this job is not any more in the latest pipeline run.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run a scheduled pipeline build
2. try to obtain artefacts from that job

**Expected behaviour**
When artefacts are still present on the GitLab server, Quality Time should be able to obtain them and use them as a metric source, regardless if other pipeline builds have run.

**Screenshots**
After the scheduled pipeline build has run, QT can acquire the artefacts.
![image](https://user-images.githubusercontent.com/95095453/176588581-4b76ed30-eb41-4ab2-8c51-66e7cfc3eafa.png)

After another pipeline build has run, the same artefacts, that are still present, cannot be acquired through the API anymore.
![image](https://user-images.githubusercontent.com/95095453/176588695-c8247b38-2b93-4ba0-8213-7b42073aab74.png)

**Comment by fniessink** [comment]
Example implementation:

```console
PROJECT_ID=4
PIPELINE_ID=`curl --silent --header "PRIVATE-TOKEN: xxx" "http://gitlab.brzo.ictu/api/v4/projects/$PROJECT_ID/pipelines?scope=finished&status=success&source=schedule&order_by=updated_at" | jq ".[0] | .id"`
JOB_ID=`curl --silent --header "PRIVATE-TOKEN: xxx" "http://gitlab.brzo.ictu/api/v4/projects/$PROJECT_ID/pipelines/$PIPELINE_ID/jobs?scope=success" | jq ".[] | select(.name == \"dependency-check\") | .id"`
curl --output artifacts.zip --header "PRIVATE-TOKEN: xxx" "http://gitlab.brzo.ictu/api/v4/projects/4/jobs/$JOB_ID/artifacts"
```

**Comment by fniessink** [comment]
The problem here is that the source for the security warnings metric isn't GitLab, it's a OWASP dependency report or an OWASP ZAP report. To fix this bug it seems we have to introduce a new "retrieval" mechanism for all static files. So far Quality-time expects static files to be retrievable by http(s). To fix this bug, we would have to add a new mechanism: retrieve a static file from GitLab, which uses the steps listed above. For each static source (XML/JSON/HTML files), users would need to be able to indicate whether they want to configure a http(s) URL as source location or a GitLab server.

**Comment by fniessink** [comment]
We decided not to address this issue in Quality-time. Quality-time works with the assumption that files can be downloaded from static URLs and changing that assumption is rather costly and complicates the UI:
- When selecting a source that is a file, users would need to be able to enter either a static URL or a number of GitLab parameters (GitLab URL, project, artifact path) and a way to choose between the two options.
- The collector would need to use a different mechanism for retrieving files from static URLs than from GitLab. So far, each source type has one retrieval mechanism (either get a file via HTTP(S) or get information via an API). If each file source type can also be retrieved from GitLab, the number of combinations increases significantly.

To work-around this issue we recommend to publish the artifacts  from the GitLab pipeline to some stable location, e.g. in Nexus, so that they are always available from the same URL, regardless of the pipeline running completely or not.
